version: '3.7'
services:

  web:
    build: ./alshamelah_api
    image: oratio/virgo:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./alshamelah_api:/usr/src/app
      - ./media:/usr/src/app/media
    ports:
      - "8000:8000"
      - "25:25"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    restart: always
    #    image: postgres:12.0
    build:
      context: ./compose/postgres
      dockerfile: Dockerfile
    volumes:
      - "alshamelah_db_data:/var/lib/postgresql/data"
      - ./containers_data/db/postgres/backups:/backups
    environment:
      - POSTGRES_USER=alshamelah_admin
      - POSTGRES_PASSWORD=Sy3aZdxGyQ8KWEtK
      - POSTGRES_DB=alshamelah_db
    ports:
      - 5435:5432

volumes:
  alshamelah_db_data:
    external: true
