version: '3.7'
services:
  web:
    build: ./alshamelah_api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./alshamelah_api:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    build:
      context: ./compose/postgres
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data:z
    environment:
      - POSTGRES_USER=alshamelah_admin
      - POSTGRES_PASSWORD=Sy3aZdxGyQ8KWEtK
      - POSTGRES_DB=alshamelah_db
    ports:
      - 5435:5432

volumes:
  db-data:
