# Generated by Django 3.0.7 on 2020-06-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='sid',
            field=models.CharField(default='', max_length=100, verbose_name='SID'),
            preserve_default=False,
        ),
    ]
