# Generated by Django 3.0.7 on 2020-06-29 03:16

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(choices=[('usd', 'USD')], max_length=3, verbose_name='Currency')),
                ('type', models.CharField(
                    choices=[('credit_card', 'Credit Card'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay')],
                    max_length=15, verbose_name='Payment way')),
                ('status',
                 models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')],
                                  max_length=10, verbose_name='Payment status')),
                ('execute_response', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('payment_response', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('payment_card', models.CharField(max_length=24, null=True, verbose_name='Card Number')),
                ('payment_card_type', models.CharField(max_length=50, null=True, verbose_name='Card Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments',
                                           to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Payments',
                'ordering': ['-date'],
            },
        ),
    ]
