# Generated by Django 3.0.7 on 2020-06-24 21:52

import apps.chatrooms.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Chat Room Types',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.CharField(max_length=8000, null=True, verbose_name='description')),
                ('lecturer', models.CharField(max_length=255, verbose_name='lecturer')),
                ('date', models.DateField(verbose_name='Date')),
                ('from_time', models.TimeField(verbose_name='From Time')),
                ('to_time', models.TimeField(verbose_name='To Time')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.chatrooms.models.ChatRoom.get_path)),
                ('url', models.URLField(verbose_name='Hangout Url')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatrooms.RoomType', verbose_name='Type')),
            ],
            options={
                'verbose_name_plural': 'Chatrooms',
                'ordering': ['-date', 'from_time'],
            },
        ),
    ]
