# Generated by Django 3.0.7 on 2020-07-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0003_remove_chatroom_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedDiscussion',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Archived Discussions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chatrooms.discussion',),
        ),
        migrations.CreateModel(
            name='ArchivedDiscussionRegistration',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Archived Discussion Registrations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chatrooms.discussionregistration',),
        ),
        migrations.CreateModel(
            name='ArchivedSeminar',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Archived Seminars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chatrooms.seminar',),
        ),
        migrations.CreateModel(
            name='ArchivedSeminarRegistration',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Archived Seminar Registrations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chatrooms.seminarregistration',),
        ),
    ]
