# Generated by Django 3.0.6 on 2020-06-15 00:17

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('author', models.CharField(max_length=1000, verbose_name='Author')),
                ('author_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Author Id')),
                ('has_audio', models.BooleanField(default=False, verbose_name='Has Audio')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='Publish Date')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Cover Image')),
                ('read_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Read Count')),
                ('download_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Download Count')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Page Count')),
                ('search_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Search Count')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='categories.Category', verbose_name='Category')),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='categories.SubCategory', verbose_name='Sub Category')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Uploader')),
            ],
        ),
        migrations.CreateModel(
            name='BookRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Rating')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to='books.Book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_ratings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='BookMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('audio', 'Audio'), ('pdf', 'PDF')], max_length=10, verbose_name='Type')),
                ('url', models.URLField(verbose_name='Url')),
                ('approved', models.BooleanField(verbose_name='Approved')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_media', to='books.Book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_media', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='BookMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(verbose_name='Page')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_marks', to='books.Book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_marks', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='BookHighlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(verbose_name='Page')),
                ('line', models.PositiveSmallIntegerField(verbose_name='Line')),
                ('start', models.PositiveIntegerField(verbose_name='Start')),
                ('end', models.PositiveIntegerField(verbose_name='End')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_highlights', to='books.Book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_highlights', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('page', models.PositiveSmallIntegerField(verbose_name='Page')),
                ('line', models.PositiveSmallIntegerField(verbose_name='Line')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to='books.Book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='BookAudio',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('books.bookmedia',),
        ),
        migrations.CreateModel(
            name='BookPDF',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('books.bookmedia',),
        ),
    ]
