# Generated by Django 3.0.6 on 2020-06-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAudio',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('books.bookmedia',),
        ),
        migrations.CreateModel(
            name='BookPDF',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('books.bookmedia',),
        ),
    ]
