# Generated by Django 3.0.6 on 2020-06-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookaudio_bookpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='download_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Download Count'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Page Count'),
        ),
        migrations.AlterField(
            model_name='book',
            name='read_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Read Count'),
        ),
        migrations.AlterField(
            model_name='book',
            name='search_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Search Count'),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='line',
            field=models.PositiveSmallIntegerField(verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='bookcomment',
            name='page',
            field=models.PositiveSmallIntegerField(verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='bookhighlight',
            name='end',
            field=models.PositiveIntegerField(verbose_name='End'),
        ),
        migrations.AlterField(
            model_name='bookhighlight',
            name='line',
            field=models.PositiveSmallIntegerField(verbose_name='Line'),
        ),
        migrations.AlterField(
            model_name='bookhighlight',
            name='page',
            field=models.PositiveSmallIntegerField(verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='bookhighlight',
            name='start',
            field=models.PositiveIntegerField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='page',
            field=models.PositiveSmallIntegerField(verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='bookrating',
            name='rating',
            field=models.PositiveSmallIntegerField(verbose_name='Rating'),
        ),
    ]
