# Generated by Django 3.0.7 on 2020-06-22 07:22

import apps.books.models
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0004_bookreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='approved',
            field=models.BooleanField(default=False, null=True, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True,
                                                               upload_to=apps.books.models.Book.path),
        ),
        migrations.AlterField(
            model_name='book',
            name='has_audio',
            field=models.BooleanField(default=False, null=True, verbose_name='Has Audio'),
        ),
    ]
