# Generated by Django 3.0.7 on 2020-06-22 13:19

import apps.books.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0005_auto_20200622_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='bookmedia',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AlterField(
            model_name='bookmedia',
            name='url',
            field=models.FileField(upload_to=apps.books.models.BookMedia.get_path, verbose_name='Url'),
        ),
    ]
