# Generated by Django 3.0.7 on 2020-06-22 14:58

import apps.books.models
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200622_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=apps.books.models.Book.path),
        ),
    ]
