# Generated by Django 3.0.7 on 2020-06-22 21:36

import apps.books.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20200622_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='has_audio',
        ),
        migrations.RemoveField(
            model_name='book',
            name='read_count',
        ),
        migrations.RemoveField(
            model_name='book',
            name='search_count',
        ),
        migrations.AlterField(
            model_name='book',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=apps.books.models.Book.path),
        ),
    ]
