# Generated by Django 3.0.7 on 2020-06-23 21:14

import apps.books.models
import easy_thumbnails.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0015_auto_20200623_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True,
                                                               upload_to=apps.books.models.Book.get_path),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='comment',
            field=models.TextField(null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')],
                                                   null=True, verbose_name='Rating'),
        ),
    ]
