# Generated by Django 3.0.7 on 2020-06-24 21:15

import apps.books.models
import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0016_auto_20200623_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True,
                                                               upload_to=apps.books.models.Book.get_path),
        ),
    ]
