# Generated by Django 3.0.7 on 2020-06-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_auto_20200624_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchbook',
            name='content',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Content'),
        ),
    ]
