# Generated by Django 3.0.7 on 2020-06-27 10:01

import apps.books.models
import easy_thumbnails.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0020_auto_20200625_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=easy_thumbnails.fields.ThumbnailerImageField(null=True, upload_to=apps.books.models.Book.get_path),
        ),
    ]
