# Generated by Django 3.0.7 on 2020-06-27 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0021_auto_20200627_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('books.book',),
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('books.book',),
        ),
        migrations.RemoveField(
            model_name='booksuggestion',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.CharField(max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('book', 'Book'), ('paper', 'Paper'), ('thesis', 'Thesis')], default='book',
                                   max_length=10, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booksuggestion',
            name='publish_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True,
                                                   validators=[django.core.validators.MinValueValidator(0),
                                                               django.core.validators.MaxValueValidator(2020)],
                                                   verbose_name='Publish Year'),
        ),
        migrations.AddField(
            model_name='readbook',
            name='page',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Page reached'),
        ),
    ]
