# Generated by Django 3.0.7 on 2020-06-28 00:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0022_auto_20200627_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
