# Generated by Django 3.0.7 on 2020-06-28 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0023_auto_20200628_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-creation_time']},
        ),
        migrations.AlterModelOptions(
            name='thesis',
            options={'ordering': ['-creation_time']},
        ),
    ]
