# Generated by Django 3.0.7 on 2020-06-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0024_auto_20200628_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcomment',
            name='line',
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='highlighted_text',
            field=models.TextField(default='', verbose_name='Highlighted Text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='start',
            field=models.PositiveIntegerField(default=0, verbose_name='Start'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookcomment',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
