# Generated by Django 3.0.7 on 2020-06-29 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0025_auto_20200629_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Title')),
                ('note', models.TextField(null=True, verbose_name='Note')),
                ('page', models.PositiveSmallIntegerField(verbose_name='Page')),
                ('start', models.PositiveIntegerField(verbose_name='Start')),
                ('end', models.PositiveIntegerField(verbose_name='End')),
                ('tashkeel_start', models.PositiveIntegerField(verbose_name='Tashkeel Start')),
                ('tashkeel_end', models.PositiveIntegerField(verbose_name='Tashkeel End')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_notes',
                                           to='books.Book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_notes',
                                           to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bookhighlight',
            name='book',
        ),
        migrations.RemoveField(
            model_name='bookhighlight',
            name='user',
        ),
        migrations.DeleteModel(
            name='BookComment',
        ),
        migrations.DeleteModel(
            name='BookHighlight',
        ),
    ]
