# Generated by Django 3.0.7 on 2020-07-02 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0026_auto_20200629_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookaudio',
            options={'verbose_name_plural': 'Book audio files'},
        ),
    ]
