# Generated by Django 3.0.7 on 2020-07-04 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0027_auto_20200702_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmedia',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_media', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
