# Generated by Django 3.0.7 on 2020-07-04 19:42

import apps.books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0028_auto_20200704_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(null=True, upload_to=apps.books.models.Book.get_path),
        ),
    ]
