# Generated by Django 3.0.8 on 2020-07-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0029_auto_20200704_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmedia',
            name='duration',
            field=models.PositiveIntegerField(null=True, verbose_name='Audio duration'),
        ),
    ]
