# Generated by Django 3.0.8 on 2020-07-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0030_bookmedia_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmedia',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Audio duration'),
        ),
    ]
