# Generated by Django 3.0.8 on 2020-07-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0031_auto_20200709_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbook',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
    ]
