# Generated by Django 3.0.8 on 2020-07-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0032_readbook_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='listenbook',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='Finished'),
        ),
    ]
