# Generated by Django 3.0.8 on 2020-07-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0033_listenbook_finished'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booknote',
            options={'ordering': ['-creation_time']},
        ),
    ]
