# Generated by Django 3.0.7 on 2020-07-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('points', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpoints',
            name='action_id',
            field=models.PositiveIntegerField(null=True, verbose_name='Transaction Id'),
        ),
    ]
