# Generated by Django 3.0.7 on 2020-07-03 03:54

from django.db import migrations


def insert_settings(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    point_badge = apps.get_model("points", "PointBadge")
    if not point_badge.objects.all().exists():
        point_badge.objects.bulk_create(
            [point_badge(name='New', point_num=0), point_badge(name='Active', point_num=20),
             point_badge(name='Golden', point_num=100), point_badge(name='Ultimate', point_num=1000)]
        )


class Migration(migrations.Migration):
    dependencies = [
        ('points', '0003_auto_20200703_0314'),
    ]

    operations = [
        migrations.RunPython(insert_settings),
    ]
