# Generated by Django 3.0.8 on 2020-07-12 08:18

import apps.points.models
from django.db import migrations, models

# def insert_settings(apps, schema_editor):
#     # We can't import the Person model directly as it may be a newer
#     # version than this migration expects. We use the historical version.
#     achievement = apps.get_model("points", "Achievement")
#     for _type in achievement.TYPE_CHOICES:
#         if not achievement.objects.filter(type=_type).exists():
#             achievement.objects.create(type=_type, title='Title', bronze=1, silver=20, gold=100, diamond=1000,
#                                        bronze_icon='')

class Migration(migrations.Migration):

    dependencies = [
        ('points', '0005_achievement_userachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='bronze_icon',
            field=models.ImageField(upload_to=apps.points.models.Achievement.get_path, verbose_name='Bronze Achievement Icon'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='diamond_icon',
            field=models.ImageField(upload_to=apps.points.models.Achievement.get_path, verbose_name='Diamond Achievement Icon'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='gold_icon',
            field=models.ImageField(upload_to=apps.points.models.Achievement.get_path, verbose_name='Gold Achievement Icon'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='silver_icon',
            field=models.ImageField(upload_to=apps.points.models.Achievement.get_path, verbose_name='Silver Achievement Icon'),
        ),
        # migrations.RunPython(insert_settings),
    ]
