# Generated by Django 3.0.8 on 2020-07-13 00:50

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('points', '0007_auto_20200712_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('reads', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('book_note_count', models.PositiveSmallIntegerField(default=0)),
                ('user_note_count', models.PositiveSmallIntegerField(default=0)),
                ('book_highlight_count', models.PositiveSmallIntegerField(default=0)),
                ('book_finished_count', models.PositiveSmallIntegerField(default=0)),
                ('book_review_count', models.PositiveSmallIntegerField(default=0)),
                ('book_rate_count', models.PositiveSmallIntegerField(default=0)),
                ('book_share_count', models.PositiveSmallIntegerField(default=0)),
                ('app_share_count', models.PositiveSmallIntegerField(default=0)),
                ('lecture_share_count', models.PositiveSmallIntegerField(default=0)),
                ('highlight_share_count', models.PositiveSmallIntegerField(default=0)),
                ('donation_count', models.PositiveSmallIntegerField(default=0)),
                ('minutes_listened', models.PositiveSmallIntegerField(default=0)),
                ('audio_book_finished_count', models.PositiveSmallIntegerField(default=0)),
                ('book_read_count', models.PositiveSmallIntegerField(default=0)),
                ('page_read_count', models.PositiveSmallIntegerField(default=0)),
                ('book_listened_count', models.PositiveSmallIntegerField(default=0)),
                ('max_book_pages_read', models.PositiveSmallIntegerField(default=0)),
                ('max_book_audio_minutes_listened', models.PositiveSmallIntegerField(default=0)),
                ('max_consecutive_login_days', models.PositiveSmallIntegerField(default=0)),
                ('max_daily_read', models.PositiveSmallIntegerField(default=0)),
                ('max_daily_listen', models.PositiveSmallIntegerField(default=0)),
                ('daily_read', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('daily_listen', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('last_login', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
