# Generated by Django 3.0.8 on 2020-07-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0008_userstatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatistics',
            name='last_login',
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='book_mark_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userstatistics',
            name='lecture_attendance_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
