# Generated by Django 3.0.8 on 2020-07-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0009_auto_20200713_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userachievement',
            old_name='type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='userachievement',
            name='points',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
