# Generated by Django 3.0.8 on 2020-07-16 03:53

import apps.points.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0010_auto_20200713_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='default_icon',
            field=models.ImageField(default='achievements/pages_read_number/icons/Silver.png', upload_to=apps.points.models.Achievement.get_path, verbose_name='Default Achievement Icon'),
            preserve_default=False,
        ),
    ]
