# Generated by Django 3.0.8 on 2020-07-12 09:57

from django.db import migrations, models

def insert_settings(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    urls = apps.get_model("site_data", "AppUrls")
    urls.objects.create(google='https://play.google.com/store?hl=en', apple='https://www.apple.com/ios/app-store/')

class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUrls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('google', models.CharField(max_length=1000, verbose_name='Google Play Store URL')),
                ('apple', models.CharField(max_length=1000, verbose_name='Apple Store URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(insert_settings),
    ]
