# Generated by Django 3.0.8 on 2020-07-12 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_data', '0002_appurls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appurls',
            options={'verbose_name_plural': 'App Urls'},
        ),
    ]
