# Generated by Django 3.0.7 on 2020-06-22 22:17

import apps.categories.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('categories', '0004_auto_20200622_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='last_update_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.categories.models.Category.get_path),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.categories.models.SubCategory.get_path),
        ),
    ]
