# Generated by Django 3.0.7 on 2020-06-24 21:15

import apps.categories.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('categories', '0011_auto_20200623_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.categories.models.Category.get_path),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.categories.models.SubCategory.get_path),
        ),
    ]
