# Generated by Django 3.0.6 on 2020-06-15 00:21
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('Update django_site set domain = \'{site_domain}\', name=\'{site_name}\' where id = {site_id}'
                          .format(site_domain=settings.SITE_DOMAIN, site_name=settings.SITE_NAME,
                                  site_id=settings.SITE_ID))
    ]
