# Generated by Django 3.0.7 on 2020-06-23 12:12

import apps.users.models
import django.db.models.deletion
import easy_thumbnails.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_auto_20200623_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='type',
            field=models.CharField(choices=[('E', 'Email'), ('P', 'Phone')], max_length=2, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True,
                                                               upload_to=apps.users.models.User.get_path),
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('device_id', models.CharField(max_length=255, verbose_name='Device Id')),
                ('enabled', models.BooleanField(default=True, null=True, verbose_name='Enabled')),
                ('book_added', models.BooleanField(default=True, null=True, verbose_name='Book Added')),
                ('book_approved', models.BooleanField(default=True, null=True, verbose_name='Book Approved')),
                ('audio_approved', models.BooleanField(default=True, null=True, verbose_name='Audio Approved')),
                ('user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_setting',
                                      to=settings.AUTH_USER_MODEL, verbose_name='Notification Setting')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('type', models.CharField(choices=[('book_added', 'Book Added'), ('book_approved', 'Book Approved'),
                                                   ('audio_approved', 'Audio Approved')], max_length=20,
                                          verbose_name='Type')),
                ('message', models.CharField(max_length=1000, verbose_name='Message')),
                ('read', models.BooleanField(default=False, null=True, verbose_name='Read')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications',
                                           to=settings.AUTH_USER_MODEL, verbose_name='Notifications')),
            ],
            options={
                'ordering': ['-read', '-creation_time'],
            },
        ),
    ]
