# Generated by Django 3.0.7 on 2020-06-27 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200623_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_code',
        ),
    ]
