# Generated by Django 3.0.7 on 2020-06-27 20:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0014_auto_20200627_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='_photo',
        ),
    ]
