# Generated by Django 3.0.7 on 2020-06-27 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0015_auto_20200627_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='_photo',
            new_name='photo',
        ),
    ]
