# Generated by Django 3.0.7 on 2020-07-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200629_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='book_added',
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='admin_notifications',
            field=models.BooleanField(default=True, null=True, verbose_name='Admin Notifications'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='paper_approved',
            field=models.BooleanField(default=True, null=True, verbose_name='Paper Approved'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='payment_processed',
            field=models.BooleanField(default=True, null=True, verbose_name='Payment Processed'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='points_awarded',
            field=models.BooleanField(default=True, null=True, verbose_name='Points Awarded'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='support_requested',
            field=models.BooleanField(default=True, null=True, verbose_name='Support Requested'),
        ),
        migrations.AddField(
            model_name='notificationsetting',
            name='thesis_approved',
            field=models.BooleanField(default=True, null=True, verbose_name='Thesis Approved'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('book_approved', 'Book Approved'), ('paper_approved', 'Paper Approved'), ('thesis_approved', 'Thesis Approved'), ('audio_approved', 'Audio Approved'), ('payment_success', 'Payment Success'), ('payment_rejected', 'Payment Rejected'), ('support_request', 'Support Request'), ('points_awarded', 'Points awarded'), ('admin_notification', 'Admin Notification')], max_length=20, verbose_name='Type'),
        ),
    ]
