# Generated by Django 3.0.7 on 2020-07-02 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20200702_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.CharField(max_length=1000, verbose_name='Message')),
                ('user', models.ManyToManyField(related_name='custom_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Custom Notifications')),
            ],
            options={
                'ordering': ['-creation_time'],
            },
        ),
    ]
