# Generated by Django 3.0.7 on 2020-07-02 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_customnotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customnotification',
            name='user',
        ),
        migrations.AddField(
            model_name='customnotification',
            name='users',
            field=models.ManyToManyField(related_name='custom_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Notify Users (with notification enabled)'),
        ),
    ]
