# Generated by Django 3.0.7 on 2020-07-03 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0020_auto_20200702_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnotification',
            name='users',
            field=models.ManyToManyField(related_name='custom_notifications', to=settings.AUTH_USER_MODEL,
                                         verbose_name='Notify Users \n(with notification enabled)'),
        ),
    ]
