# Generated by Django 3.0.8 on 2020-07-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20200703_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordOTP',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.otp',),
        ),
        migrations.AlterField(
            model_name='otp',
            name='type',
            field=models.CharField(choices=[('E', 'Email'), ('P', 'Phone'), ('PW', 'Passwod')], max_length=2, verbose_name='Type'),
        ),
    ]
