# Generated by Django 3.0.8 on 2020-07-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_remove_user_membership'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-creation_time']},
        ),
    ]
