# Generated by Django 3.0.7 on 2020-06-27 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Discussions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chatrooms.chatroom',),
        ),
        migrations.CreateModel(
            name='DiscussionRegistration',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Discussion Registrations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chatrooms.chatroom',),
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Seminars',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chatrooms.chatroom',),
        ),
        migrations.CreateModel(
            name='SeminarRegistration',
            fields=[
            ],
            options={
                'verbose_name_plural': 'Seminar Registrations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chatrooms.chatroom',),
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name_plural': 'Chat Room Categories'},
        ),
        migrations.AddField(
            model_name='chatroom',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='chatrooms.RoomType',
                                    verbose_name='Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='type',
            field=models.CharField(choices=[('seminar', 'Seminar'), ('discussion', 'Discussion')], max_length=10,
                                   verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='ChatRoomRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True)),
                ('chat_room',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations',
                                   to='chatrooms.ChatRoom', verbose_name='Chat Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations',
                                           to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
